const mongoose = require('mongoose');
const ProgramName = require('../models/ProgramNameModel');

const DATABASE_URL = 'mongodb+srv://adi:AGmChskREizfDNlc@cluster0.o9lpe.mongodb.net/naavi-mock';

const programNames = [
  { name: 'Bachelors in Accounting' },
  { name: 'Bachelors in Acting' },
  { name: 'Bachelors in Actuarial Science' },
  { name: 'Bachelors in Advertising' },
  { name: 'Bachelors in Advertising Design' },
  { name: 'Bachelors in Aerospace Engineering' },
  { name: 'Bachelors in Agricultural Engineering' },
  { name: 'Bachelors in Agricultural Science' },
  { name: 'Bachelors in Animation & Visual Effects' },
  { name: 'Bachelors in Anthropology' },
  { name: 'Bachelors in Arabic' },
  { name: 'Bachelors in Architecture' },
  { name: 'Bachelors in Art History' },
  { name: 'Bachelors in Artificial Intelligence' },
  { name: 'Bachelors in Astronomy & Astrophysics' },
  { name: 'Bachelors in Athletic Training' },
  { name: 'Bachelors in Automotive Engineering' },
  { name: 'Bachelors in Aviation' },
  { name: 'Bachelors in Banking & Finance' },
  { name: 'Bachelors in Behavioral Science' },
  { name: 'Bachelors in Biochemistry' },
  { name: 'Bachelors in Biology' },
  { name: 'Bachelors in Biomedical Engineering' },
  { name: 'Bachelors in Biotechnology' },
  { name: 'Bachelors in Botany' },
  { name: 'Bachelors in Broadcasting' },
  { name: 'Bachelors in Business Administration' },
  { name: 'Bachelors in Business Analytics' },
  { name: 'Bachelors in Chemical Engineering' },
  { name: 'Bachelors in Chemistry' },
  { name: 'Bachelors in Child Development' },
  { name: 'Bachelors in Chinese (Mandarin)' },
  { name: 'Bachelors in Civil Engineering' },
  { name: 'Bachelors in Classics' },
  { name: 'Bachelors in Climate Science' },
  { name: 'Bachelors in Clinical Psychology' },
  { name: 'Bachelors in Cloud Computing' },
  { name: 'Bachelors in Comparative Literature' },
  { name: 'Bachelors in Computer Engineering' },
  { name: 'Bachelors in Computer Networking' },
  { name: 'Bachelors in Computer Science' },
  { name: 'Bachelors in Conservation Biology' },
  { name: 'Bachelors in Construction Management' },
  { name: 'Bachelors in Cosmetology Management' },
  { name: 'Bachelors in Counseling' },
  { name: 'Bachelors in Creative Writing' },
  { name: 'Bachelors in Criminal Justice' },
  { name: 'Bachelors in Criminology' },
  { name: 'Bachelors in Culinary Arts' },
  { name: 'Bachelors in Culinary Arts Management' },
  { name: 'Bachelors in Cultural Studies' },
  { name: 'Bachelors in Cybersecurity' },
  { name: 'Bachelors in Dance' },
  { name: 'Bachelors in Data Science' },
  { name: 'Bachelors in Dental Hygiene' },
  { name: 'Bachelors in Development Studies' },
  { name: 'Bachelors in Digital Marketing' },
  { name: 'Bachelors in Digital Media' },
  { name: 'Bachelors in E-Commerce' },
  { name: 'Bachelors in Early Childhood Education' },
  { name: 'Bachelors in Ecology' },
  { name: 'Bachelors in Economics' },
  { name: 'Bachelors in Educational Psychology' },
  { name: 'Bachelors in Electrical Engineering' },
  { name: 'Bachelors in Elementary Education' },
  { name: 'Bachelors in Emergency Management' },
  { name: 'Bachelors in English & Literature' },
  { name: 'Bachelors in Entrepreneurship' },
  { name: 'Bachelors in Environmental Engineering' },
  { name: 'Bachelors in Environmental Science' },
  { name: 'Bachelors in Environmental Studies' },
  { name: 'Bachelors in Event Management' },
  { name: 'Bachelors in Exercise Science' },
  { name: 'Bachelors in Family Studies' },
  { name: 'Bachelors in Fashion Design' },
  { name: 'Bachelors in Fashion Merchandising' },
  { name: 'Bachelors in Film & Television Production' },
  { name: 'Bachelors in Film Studies' },
  { name: 'Bachelors in Finance' },
  { name: 'Bachelors in Fine Arts' },
  { name: 'Bachelors in Fire Science' },
  { name: 'Bachelors in Food Science & Technology' },
  { name: 'Bachelors in Forensic Science' },
  { name: 'Bachelors in Forestry' },
  { name: 'Bachelors in French' },
  { name: 'Bachelors in Game Art & Design' },
  { name: 'Bachelors in Game Design' },
  { name: 'Bachelors in Game Development' },
  { name: 'Bachelors in Gender Studies' },
  { name: 'Bachelors in Genetics' },
  { name: 'Bachelors in Geography' },
  { name: 'Bachelors in Geology' },
  { name: 'Bachelors in German' },
  { name: 'Bachelors in Gerontology' },
  { name: 'Bachelors in Graphic Design' },
  { name: 'Bachelors in Health Information Management' },
  { name: 'Bachelors in Healthcare Administration' },
  { name: 'Bachelors in History' },
  { name: 'Bachelors in Homeland Security' },
  { name: 'Bachelors in Hospitality Management' },
  { name: 'Bachelors in Human Resource Management' },
  { name: 'Bachelors in Human Rights' },
  { name: 'Bachelors in Human Services' },
  { name: 'Bachelors in Human-Computer Interaction' },
  { name: 'Bachelors in Illustration' },
  { name: 'Bachelors in Industrial Design' },
  { name: 'Bachelors in Industrial Engineering' },
  { name: 'Bachelors in Information Systems' },
  { name: 'Bachelors in Information Technology' },
  { name: 'Bachelors in Insurance' },
  { name: 'Bachelors in Interdisciplinary Studies' },
  { name: 'Bachelors in Interior Design' },
  { name: 'Bachelors in International Business' },
  { name: 'Bachelors in International Relations' },
  { name: 'Bachelors in Italian' },
  { name: 'Bachelors in Japanese' },
  { name: 'Bachelors in Jazz Studies' },
  { name: 'Bachelors in Journalism' },
  { name: 'Bachelors in Kinesiology' },
  { name: 'Bachelors in Korean' },
  { name: 'Bachelors in Landscape Architecture' },
  { name: 'Bachelors in Liberal Arts' },
  { name: 'Bachelors in Linguistics' },
  { name: 'Bachelors in Management' },
  { name: 'Bachelors in Management Information Systems' },
  { name: 'Bachelors in Marine Biology' },
  { name: 'Bachelors in Marine Engineering' },
  { name: 'Bachelors in Marketing' },
  { name: 'Bachelors in Mass Communication' },
  { name: 'Bachelors in Materials Engineering' },
  { name: 'Bachelors in Mathematics' },
  { name: 'Bachelors in Mechanical Engineering' },
  { name: 'Bachelors in Mechatronics Engineering' },
  { name: 'Bachelors in Media Studies' },
  { name: 'Bachelors in Medical Imaging' },
  { name: 'Bachelors in Medical Laboratory Science' },
  { name: 'Bachelors in Microbiology' },
  { name: 'Bachelors in Military Science' },
  { name: 'Bachelors in Music Business' },
  { name: 'Bachelors in Music Composition' },
  { name: 'Bachelors in Music Education' },
  { name: 'Bachelors in Music Performance' },
  { name: 'Bachelors in Music Production' },
  { name: 'Bachelors in Music Theory' },
  { name: 'Bachelors in Musical Theatre' },
  { name: 'Bachelors in Neuroscience' },
  { name: 'Bachelors in Nuclear Engineering' },
  { name: 'Bachelors in Nursing' },
  { name: 'Bachelors in Nutrition & Dietetics' },
  { name: 'Bachelors in Occupational Therapy' },
  { name: 'Bachelors in Oceanography' },
  { name: 'Bachelors in Operations Management' },
  { name: 'Bachelors in Optometry' },
  { name: 'Bachelors in Painting' },
  { name: 'Bachelors in Paralegal Studies' },
  { name: 'Bachelors in Paramedic Science' },
  { name: 'Bachelors in Performing Arts' },
  { name: 'Bachelors in Petroleum Engineering' },
  { name: 'Bachelors in Pharmacy' },
  { name: 'Bachelors in Philosophy' },
  { name: 'Bachelors in Photography' },
  { name: 'Bachelors in Physical Education' },
  { name: 'Bachelors in Physical Education & Coaching' },
  { name: 'Bachelors in Physical Therapy' },
  { name: 'Bachelors in Physics' },
  { name: 'Bachelors in Political Communication' },
  { name: 'Bachelors in Political Science' },
  { name: 'Bachelors in Portuguese' },
  { name: 'Bachelors in Pre-Law' },
  { name: 'Bachelors in Pre-Medicine' },
  { name: 'Bachelors in Project Management' },
  { name: 'Bachelors in Psychology' },
  { name: 'Bachelors in Public Administration' },
  { name: 'Bachelors in Public Health' },
  { name: 'Bachelors in Public Policy' },
  { name: 'Bachelors in Public Relations' },
  { name: 'Bachelors in Radiologic Technology' },
  { name: 'Bachelors in Real Estate' },
  { name: 'Bachelors in Religious Studies' },
  { name: 'Bachelors in Respiratory Therapy' },
  { name: 'Bachelors in Retail Management' },
  { name: 'Bachelors in Robotics Engineering' },
  { name: 'Bachelors in Russian' },
  { name: 'Bachelors in STEM Education' },
  { name: 'Bachelors in Screenwriting' },
  { name: 'Bachelors in Sculpture' },
  { name: 'Bachelors in Secondary Education' },
  { name: 'Bachelors in Sign Language Studies' },
  { name: 'Bachelors in Social Media & Content Creation' },
  { name: 'Bachelors in Social Work' },
  { name: 'Bachelors in Sociology' },
  { name: 'Bachelors in Software Engineering' },
  { name: 'Bachelors in Songwriting' },
  { name: 'Bachelors in Spanish' },
  { name: 'Bachelors in Special Education' },
  { name: 'Bachelors in Speech & Language Pathology' },
  { name: 'Bachelors in Sports Management' },
  { name: 'Bachelors in Sports Science' },
  { name: 'Bachelors in Statistics' },
  { name: 'Bachelors in Strategic Communication' },
  { name: 'Bachelors in Structural Engineering' },
  { name: 'Bachelors in Supply Chain Management' },
  { name: 'Bachelors in Surgical Technology' },
  { name: 'Bachelors in Sustainable Energy' },
  { name: 'Bachelors in Systems Engineering' },
  { name: 'Bachelors in Theatre & Drama' },
  { name: 'Bachelors in Tourism & Travel Management' },
  { name: 'Bachelors in UX/UI Design' },
  { name: 'Bachelors in Urban Planning' },
  { name: 'Bachelors in Urban Studies' },
  { name: 'Bachelors in Veterinary Technology' },
  { name: 'Bachelors in Water Resource Management' },
  { name: 'Bachelors in Web Development' },
  { name: 'Bachelors in Wildlife Management' },
  { name: 'Bachelors in Zoology' },
];

mongoose
  .connect(DATABASE_URL, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(async () => {
    console.log('✅ Connected to MongoDB');
    await ProgramName.deleteMany({});
    console.log('🗑️  Old program names cleared');
    await ProgramName.insertMany(programNames);
    console.log('✅ 215 program names inserted successfully');
    mongoose.connection.close();
  })
  .catch((err) => {
    console.error('❌ Error:', err);
    mongoose.connection.close();
  });